[package]
name = "lambash"
version = "0.1.0"
authors = ["Nathan Lilienthal <nathan@nixpulvis.com>"]
edition = "2018"

[dependencies]
docopt = "*"
lalrpop-lambda = { path = "../lalrpop-lambda" }
oursh = { path = "../oursh" }
nix = "*"
